version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: lab_dis
    restart: unless-stopped
    # user: "501:20"
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      -
        type: bind
        source: ./postgres
        target: /var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: lab_dis_mysql
    restart: unless-stopped
#    user: "501:20"
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql